# https://cloud.baidu.com/doc/WENXINWORKSHOP/s/flfmc9do2
baidu:
  wenxin:
    appName: aimpalaApp
    appid: 4023966
    apiKey: FlIOVgTq5LdOW8o2KNP5ixAM
    secretKey: uN6VxzLQXCSdXx6Wna9x6AcXU2eDjZ3G

logging:
  level:
    com.yisoo: debug
    org.springframework: warn