# https://cloud.baidu.com/doc/WENXINWORKSHOP/s/flfmc9do2
baidu:
  wenxin:
    appName: 123
    appid: 123
    apiKey: 123
    secretKey: 123

logging:
  level:
    com.yisoo: debug
    org.springframework: warn